stages:
  data_processing:
    cmd: python src/data/data_processing.py
    deps:
      - src/data/data_processing.py
      - data/raw/fights_dataset_with_stats.csv
    outs:
      - data/processed

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/processed/train_processed.csv
      - params.yaml
    outs:
      - model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - data/processed/test_processed.csv
      - model.pkl
    outs:
      - model_logs.txt
